# 设置内网以便域名访问
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.1
    - 127.0.0.1
    - ::1
# MQTT配置 - 所有MQTT设备放在同一个mqtt:块中
mqtt:
  # 传感器配置
  sensor:
    - name: "鱼缸环境温度"
      unique_id: "fish_tank_env_temp"
      state_topic: "home/fish_tank/sensor/temperature/state"
      unit_of_measurement: "°C"
      device_class: "temperature"
      availability_topic: "home/fish_tank/status"
      payload_available: "online"
      payload_not_available: "offline"
      device:
        identifiers: ["fish_tank_monitor_01"]
        name: "智能鱼缸监控系统"
        manufacturer: "DIY"
        model: "ESP32 Fish Tank v1.0"
        sw_version: "1.0"

    - name: "鱼缸环境湿度"
      unique_id: "fish_tank_env_humidity"
      state_topic: "home/fish_tank/sensor/humidity/state"
      unit_of_measurement: "%"
      device_class: "humidity"
      availability_topic: "home/fish_tank/status"
      device:
        identifiers: ["fish_tank_monitor_01"]

    - name: "鱼缸水温"
      unique_id: "fish_tank_water_temp"
      state_topic: "home/fish_tank/sensor/water_temp/state"
      unit_of_measurement: "°C"
      device_class: "temperature"
      availability_topic: "home/fish_tank/status"
      device:
        identifiers: ["fish_tank_monitor_01"]

    - name: "鱼缸TDS值"
      unique_id: "fish_tank_tds"
      state_topic: "home/fish_tank/sensor/tds/state"
      unit_of_measurement: "ppm"
      icon: "mdi:water-percent"
      availability_topic: "home/fish_tank/status"
      device:
        identifiers: ["fish_tank_monitor_01"]

    - name: "鱼缸喂食次数"
      unique_id: "fish_tank_feed_count"
      state_topic: "home/fish_tank/sensor/feed_count/state"
      icon: "mdi:counter"
      availability_topic: "home/fish_tank/status"
      device:
        identifiers: ["fish_tank_monitor_01"]
# 强硬写法，让时间显示正确（如果显示不正确请修改）
    - name: "最后喂食时间"
      unique_id: "fish_tank_feed_lastFeedTime"
      state_topic: "home/fish_tank/sensor/feed_lastFeedTime/state"
      value_template: >-
        {% set timestamp = value | int %}
        {% set corrected_timestamp = timestamp - (8 * 3600)  %}  {# 减去7小时 #}
        {{ corrected_timestamp | timestamp_custom('%m-%d %H:%M', true) }}
      icon: "mdi:clock"
      availability_topic: "home/fish_tank/status"
      device:
        identifiers: ["fish_tank_monitor_01"]

    - name: "下次喂食时间"
      unique_id: "fish_tank_feed_NextFeedingTime"
      state_topic: "home/fish_tank/sensor/feed_NextFeedingTime/state"
      icon: "mdi:counter"
      availability_topic: "home/fish_tank/status"
      device:
        identifiers: ["fish_tank_monitor_01"]

  # 按钮配置
  button:
    - name: "鱼缸喂食"
      unique_id: "fish_tank_feed_button"
      command_topic: "home/fish_tank/feed/set"
      payload_press: "ON"
      availability_topic: "home/fish_tank/status"
      device:
        identifiers: ["fish_tank_monitor_01"]
      icon: "mdi:fish"

  # 开关配置
  switch:
    - name: "鱼缸自动喂食"
      unique_id: "fish_tank_auto_feeding"
      command_topic: "home/fish_tank/feedingScheduleEnabled/set"
      state_topic: "home/fish_tank/feedingScheduleEnabled/state"
      payload_on: "ON"
      payload_off: "OFF"
      device:
        identifiers: ["fish_tank_monitor_01"]
      icon: "mdi:fish"

    # 视频流开关
    - name: "鱼缸视频流开关"
      unique_id: "fish_tank_camera_stream_switch"
      command_topic: "home/fish_tank/camera/stream/set"
      state_topic: "home/fish_tank/camera/stream/state"
      payload_on: "ON"
      payload_off: "OFF"
      icon: mdi:camera
      availability_topic: "home/fish_tank/status"
      payload_available: "online"
      payload_not_available: "offline"
      device:
        identifiers: ["fish_tank_monitor_01"]

  # 数字输入配置
  number:
    - name: "第一次喂食时间"
      unique_id: "fish_tank_first_feeding_hour"
      command_topic: "home/fish_tank/feedingTime1/set"
      state_topic: "home/fish_tank/feedingTime1/state"
      min: 0
      max: 23
      step: 1
      mode: "box"
      unit_of_measurement: "时"
      device:
        identifiers: ["fish_tank_monitor_01"]
      icon: "mdi:clock-outline"
    
    - name: "第二次喂食时间"
      unique_id: "fish_tank_second_feeding_hour"
      command_topic: "home/fish_tank/feedingTime2/set"
      state_topic: "home/fish_tank/feedingTime2/state"
      min: 0
      max: 23
      step: 1
      mode: "box"
      unit_of_measurement: "时"
      device:
        identifiers: ["fish_tank_monitor_01"]
      icon: "mdi:clock-outline"
    
